//! Domain Authority Lookup (§2.5.1)
//!
//! domain_auth must NOT be generated by the model (Forbidden Model Writes).
//! Populate from a static YAML file at project root: domain_authority.yaml.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::Path;
use std::time::{Duration, SystemTime};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DomainAuthorityConfig {
    pub default: f32,
    pub overrides: HashMap<String, f32>,
}

impl Default for DomainAuthorityConfig {
    fn default() -> Self {
        let mut overrides = HashMap::new();
        overrides.insert("stdlib_docs".to_string(), 0.99);
        overrides.insert("official_sdk".to_string(), 0.95);
        overrides.insert("github.com".to_string(), 0.75);
        overrides.insert("stackoverflow.com".to_string(), 0.65);
        overrides.insert("local_file".to_string(), 1.00);
        Self {
            default: 0.50,
            overrides,
        }
    }
}

impl DomainAuthorityConfig {
    /// Load from YAML file, falling back to defaults if missing
    pub fn load(path: &Path) -> Self {
        match fs::read_to_string(path) {
            Ok(content) => serde_yaml::from_str(&content).unwrap_or_default(),
            Err(_) => Self::default(),
        }
    }

    /// Get domain authority for a URL or path.
    /// Matches against the overrides map by checking if the URL contains
    /// the override key as a substring (for domain matching).
    pub fn get_domain_auth(&self, url: &str) -> f32 {
        // Local file paths get local_file authority
        if url.starts_with("file://") || url.starts_with('/') || url.starts_with("./") {
            return *self.overrides.get("local_file").unwrap_or(&self.default);
        }

        // Check each override key against the URL
        for (key, auth) in &self.overrides {
            if url.contains(key) {
                return *auth;
            }
        }

        self.default
    }
}

/// Compute recency_factor for a local file (§2.5.1).
///
/// - Files modified within the current session get 1.0
/// - Files older than 30 days get 0.85
/// - Files older than 180 days get 0.70
pub fn compute_recency_factor(path: &Path) -> f32 {
    let Ok(metadata) = fs::metadata(path) else {
        return 0.70; // Can't stat -> assume old
    };
    let Ok(modified) = metadata.modified() else {
        return 0.70;
    };
    let age = SystemTime::now()
        .duration_since(modified)
        .unwrap_or(Duration::from_secs(0));

    let days = age.as_secs() / 86400;
    if days <= 1 {
        1.0
    } else if days <= 30 {
        0.85 + 0.15 * (1.0 - days as f32 / 30.0) // smooth gradient
    } else if days <= 180 {
        0.70 + 0.15 * (1.0 - (days - 30) as f32 / 150.0)
    } else {
        0.70
    }
}

/// Extract root domain from a URL for diversity index computation.
/// e.g., "https://docs.python.org/3/library/json.html" -> "python.org"
pub fn extract_root_domain(url: &str) -> String {
    // Handle local files
    if url.starts_with("file://") || url.starts_with('/') || url.starts_with("./") {
        return "local_file".to_string();
    }

    // Strip protocol
    let without_proto = url
        .strip_prefix("https://")
        .or_else(|| url.strip_prefix("http://"))
        .unwrap_or(url);

    // Get hostname
    let hostname = without_proto.split('/').next().unwrap_or(without_proto);

    // Extract root domain (last two parts)
    let parts: Vec<&str> = hostname.split('.').collect();
    if parts.len() >= 2 {
        format!("{}.{}", parts[parts.len() - 2], parts[parts.len() - 1])
    } else {
        hostname.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_domain_auth_defaults() {
        let cfg = DomainAuthorityConfig::default();
        assert_eq!(cfg.get_domain_auth("https://github.com/user/repo"), 0.75);
        assert_eq!(
            cfg.get_domain_auth("https://stackoverflow.com/questions/123"),
            0.65
        );
        assert_eq!(cfg.get_domain_auth("https://random-blog.com"), 0.50);
        assert_eq!(cfg.get_domain_auth("/home/user/project/src/main.py"), 1.00);
        assert_eq!(cfg.get_domain_auth("file:///etc/config"), 1.00);
    }

    #[test]
    fn test_extract_root_domain() {
        assert_eq!(
            extract_root_domain("https://docs.python.org/3/library/json.html"),
            "python.org"
        );
        assert_eq!(
            extract_root_domain("https://github.com/user/repo"),
            "github.com"
        );
        assert_eq!(
            extract_root_domain("/home/user/file.py"),
            "local_file"
        );
    }
}
